name: New Concept
description: Recommend a new concept for the Unified Astronomy Thesaurus.
title: "[New Concept]: "
labels: ["add concept"]
assignees:
  - katieefrey
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to recommend a new concept!
  - type: input
    id: concept-description
    attributes:
      label: Describe the Concept
      description: Tell us about this new concept. What does it mean? Is it more general or specific?  How does it relate to the fields of astronomy and astrophysics? Can you describe the relationship this concept has with ones that already exist in the UAT?
    validations:
      required: true
  - type: textarea
    id: concept-location
    attributes:
      label: Concept Location
      description: Under which main topic(s) would you categorize this concept? Can you describe a specific location where it fits within the current hierarchy? Should it be found in multiple locations?
  - type: textarea
    id: supporting-info
    attributes:
      label: Supporting Information
      description: To help us verify the recommended concept, please provide references to articles or reputable websites that support the use of this concept.  This could be a list of bibcodes, article citations, urls, etc. (optional)
    validations:
      required: false
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: Please include any other thoughts or relevant details related to this concept. (optional)
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/astrothesaurus/UAT/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
